// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFElLrTwwNb-R4fv4gKZifiXcLyZ79BR8',
    appId: '1:11034977466:web:68c66fd7abbd9c6d8f4e83',
    messagingSenderId: '11034977466',
    projectId: 'chat-7d730',
    authDomain: 'chat-7d730.firebaseapp.com',
    storageBucket: 'chat-7d730.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo8flZEo_-fdJvcJJnhbP_SD404aa8ME0',
    appId: '1:11034977466:android:c6b58c8b5f57c8f88f4e83',
    messagingSenderId: '11034977466',
    projectId: 'chat-7d730',
    storageBucket: 'chat-7d730.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFElLrTwwNb-R4fv4gKZifiXcLyZ79BR8',
    appId: '1:11034977466:web:d60c0e0d928eb5748f4e83',
    messagingSenderId: '11034977466',
    projectId: 'chat-7d730',
    authDomain: 'chat-7d730.firebaseapp.com',
    storageBucket: 'chat-7d730.firebasestorage.app',
  );
}
